### PR TITLE
04 eye and head gaze tracking

### PR DESCRIPTION
**Pull request by aprilgittens**
I have 4 more questions to complete for projects. Will add those tomorrow.

### CODE REVIEW

**Comment by aprilgittens** [comment]
Still working on auto-scroll. Took a while to get it working properly but I have it working now. 

Will add the following on Monday:
•	How to use eye-tracking for auto scroll
•	How to setup head tracking
•	How to visualize eye tracking data
•	What are the security concerns with using eye-tracking?

**Comment by aprilgittens** [comment]
When you're back, could you provide me with an example for 'how to visualize eye tracking data?'. Thanks!

**Comment by Yonet** [comment]
> When you're back, could you provide me with an example for 'how to visualize eye tracking data?'. Thanks!

Did you check out the MRTK example?  https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_Main.html

**Comment by aprilgittens** [comment]
@Yonet I think there's a disconnect on what do you mean by 'data'. What is the 'data' that should be visualized? When I think of 'data', I assume you want to see coordinates in a panel somewhere for where the user is looking.

**Comment by Yonet** [comment]
> @Yonet I think there's a disconnect on what do you mean by 'data'. What is the 'data' that should be visualized? When I think of 'data', I assume you want to see coordinates in a panel somewhere for where the user is looking.

Yes, I am talking about the coordinates. Have you clicked on the link that I've added for MRTK example? There is a heatmap example.

**Comment by aprilgittens** [comment]
@Yonet just finished changing the titles to lowercase. This lesson is now complete as well.

**Pull request merged**
