### PR TITLE
03 hand interactions and controllers

### PR DESCRIPTION
**Pull request by aprilgittens**
Hey Aysegul

This is a new PR for lesson 3 project. Please review and confirm that you're able to view content and images. I will wait to redo lesson 4 after receiving confirmation that the merge for lesson 3 was successful and appears in the gitbook.

Thanks!

### CODE REVIEW

**Review by Yonet — CHANGES_REQUESTED** [review]
Hi April, thank you for resending your PR. Some of the pages have the correct urls but most of them don't. See the images below. Can you check that please.
audio

buttonPrefab

**Comment by aprilgittens** [comment]
@Yonet it was a **stupid** mistake that I just figured out. The file extension was in all caps for the images. Updating now and will tag you in a comment once it's complete.

**Comment by aprilgittens** [comment]
@Yonet just confirmed that I'm able to see all images here in GitHub for pages that I wrote. Please confirm that you're able to see as well - thanks!

**Comment by Yonet** [comment]
Some extentions are still all caps and I do not see them on here: https://github.com/aprilspeight/AzureMixedRealityDocs/blob/03-hand-interactions-and-controllers/.gitbook/assets/audio_source.PNG

Check them all please and flattened the one nested folder. Can you also add links in the project readme as the example here: https://yonet.gitbook.io/mixed-reality-docs/-LyabGI7hCYwXIO2T9sV/lessons/lesson-5/project.

Thanks!

**Comment by aprilgittens** [comment]
@Yonet i didn't change the file extensions for the picture files in the assets folder - i only updated the extensions in each markdown file wherever an image is in the file. Could you clarify which project markdown file still does not have images appearing?

**Comment by aprilgittens** [comment]
@Yonet I updated the project readme with links and flattened the nested folder.

**Pull request merged**
